services:
  rtc-api-server:
    container_name: rtc-api
    depends_on:
    - rtc-first-mysql-server
    environment:
    - APP_ENV=sample
    - IS_RTC_API=Y
    image: relaxed/rtc-api
    ports:
    - 8080:8080
    restart: always
  rtc-first-mysql-server:
    container_name: rtc-first-mysql
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    image: mysql:5.7.22
    ports:
    - 3306
    volumes:
    - ./settings.sql:/docker-entrypoint-initdb.d/settings.sql
  rtc-base-mysql-server:
    container_name: rtc-base-mysql
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    image: mysql:5.7.22
    ports:
    - 3311:3306
    volumes:
    - ./basedata.sql:/docker-entrypoint-initdb.d/basedata.sql
version: "3"
