database:
  driver: mysql
  connection: root:1234@tcp(127.0.0.1:3310)/rtc?charset=utf8&parseTime=True&loc=UTC
  logger:
    kafka:
      brokers:
        - 127.0.0.1:9092
      topic: sqllog
behaviorLog:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: behaviorlog
serviceName: rtc-api
httpport: 8080